Use more generic error msg for elasticsearch-out index errors
This will break the rollup functionality of error handling and could cause a
flood, or maybe even feedback loop:

> max_bytes_length_exceeded_exception: bytes can be at most 32766 in length; got 33035

Prefer this instead:

> max_bytes_length_exceeded_exception